"""
Request DTO Abstraction Module.

This module defines the base request DTO interface that all request
DTOs should inherit from. It enforces common fields and validation
rules for all incoming requests.

Usage:
    >>> from dtos.requests.abstraction import IRequestDTO
    >>>
    >>> class MyRequestDTO(IRequestDTO):
    ...     custom_field: str
"""

import uuid

from pydantic import BaseModel, field_validator


class IRequestDTO(BaseModel):
    """
    Abstract base class for all request DTOs.

    This base class defines common fields and validation rules that
    all request DTOs must include. Currently, it requires a reference
    number for request tracking.

    Attributes:
        reference_number (str): A valid UUID string for request identification.
            Used for client-side request tracking and correlation.

    Validation:
        - reference_number must not be empty
        - reference_number must be a valid UUID format

    Example:
        >>> from dtos.requests.abstraction import IRequestDTO
        >>>
        >>> class OrderRequestDTO(IRequestDTO):
        ...     product_id: str
        ...     quantity: int
        ...
        >>> # Valid request
        >>> request = OrderRequestDTO(
        ...     reference_number="550e8400-e29b-41d4-a716-446655440000",
        ...     product_id="prod-123",
        ...     quantity=2
        ... )
        >>>
        >>> # Invalid - not a UUID
        >>> request = OrderRequestDTO(
        ...     reference_number="not-a-uuid",  # Raises ValueError
        ...     product_id="prod-123",
        ...     quantity=2
        ... )

    Note:
        The reference_number is typically generated by the client and
        passed in the request body. It's different from the server-side
        URN (Unique Request Number) which is generated by middleware.
    """

    reference_number: str
    """Client-provided UUID for request identification and tracking."""

    @field_validator('reference_number')
    @classmethod
    def validate_reference_number(cls, v: str) -> str:
        """
        Validate that reference_number is a non-empty valid UUID.

        Args:
            v (str): The reference number to validate.

        Returns:
            str: The validated reference number.

        Raises:
            ValueError: If the reference number is empty or not a valid UUID.
        """
        if not v or not v.strip():
            raise ValueError('Reference number cannot be empty.')
        try:
            uuid.UUID(v)
        except Exception:
            raise ValueError('Reference number must be a valid UUID.')
        return v
